---
apache_listen_port: 8080
apache_vhosts:
  - {servername: "1.example.com", documentroot: "/var/www/vhosts/1"}
  - {servername: "2.example.com", documentroot: "/var/www/vhosts/2"}
  - {servername: "3.example.com", documentroot: "/var/www/vhosts/3"}
  - {servername: "4.example.com", documentroot: "/var/www/vhosts/4"}
  - {servername: "5.example.com", documentroot: "/var/www/vhosts/5"}
hosts_file_to_populate: "/etc/hosts"
hosts_file_ansible_group_to_hosts_file: "{{ groups.extra_dns }}"
hosts_ip_source: "template"

# TODO. some kind of jinja2 | map to map the apache_vhosts to this?
haproxy_backend_servers:
  - name: app1
    address: 1.example.com:8080
    weight: 1
  - name: app2
    address: 2.example.com:8080
    weight: 100
  - name: app3
    address: 3.example.com:8080
    weight: 256
#
# these are the same as in the role, but we re-use this in the ops_playbooks
haproxy_socket: "/var/lib/haproxy/stats"
haproxy_backend_name: "habackend"
...
