---

 - name: do the
   hosts: lab
   become: True
   gather_facts: False
   tasks: 
   - yum:
       name: "{{ item }}"
       state: installed
     with_items:
      - "php"
      - "nc"
      - "socat"

   roles:
     - ansible-role-hosts-inventory

 - name: do the httpd and content
   hosts: lab
   become: True
   roles:
     - ansible-role-apache
     - httpd_content

 - name: do the lb
   hosts: lab
   become: True
   roles:
     - ansible-role-haproxy
