---

 - name: install some extra programs and setup /etc/hosts entries
   hosts: lab
   become: True
   gather_facts: False
   tasks: 
   - yum:
       name: "{{ item }}"
       state: installed
     with_items:
      - "php"
      - "nc"
      - "socat"
   roles:
     - ansible-role-hosts-inventory

 - name: install httpd and add content
   hosts: lab
   become: True
   roles:
     - ansible-role-apache
     - httpd_content

 - name: install and configure the load balancing
   hosts: lab
   become: True
   roles:
     - ansible-role-haproxy
